export 'day.dart';
export 'subject.dart';
export 'schedule.dart';
export 'timerange.dart';
export 'lecturer.dart';
export 'retake.dart';
export 'retakes.dart';
export 'appinfo.dart';
export 'config.dart';
